### ISSUE TITLE
Validation errors popping up randomly /signup

### ISSUE THREAD

**Issue by Mackoyokcam** [sail-point/frontend#17]
Hey @Penssake, I am getting some validation errors with the signup forms.

For the company name, whenever I type a space bar it throws the validation error for a required company name. For the email and password, as soon as I type something it throws a validation error.

**Comment by Penssake** [comment]
Hey @Mackoyokcam, I'm going to remove validation on company. We were thinking of using email on login instead of company name. Email validation makes more sense. I'll do that now.
